-- OPTIONAL (NOT REQUIRED)
-- Staff limit enforcement at DB-level via trigger.
-- Use only if you want to BLOCK any inserts that bypass the API.
-- NOTE: This will also apply to service_role inserts.

-- create or replace function public.enforce_staff_limit()
-- returns trigger language plpgsql as $$
-- declare
--   v_limit int;
--   v_active int;
-- begin
--   select staff_limit into v_limit from public.companies where id = new.company_id;
--   if v_limit is null then
--     return new;
--   end if;
--   select count(*) into v_active from public.staff where company_id = new.company_id and active = true;
--   if v_active >= v_limit then
--     raise exception 'Staff limit reached' using errcode = 'P0001';
--   end if;
--   return new;
-- end $$;
--
-- drop trigger if exists trg_enforce_staff_limit on public.staff;
-- create trigger trg_enforce_staff_limit
-- before insert on public.staff
-- for each row execute function public.enforce_staff_limit();
